### ISSUE TITLE
Makes only one documentation aka README vs ReadTheDoc

### ISSUE THREAD

**Issue by triat** [aschn/drf-tracking#105]
I saw (partially my fault) that the doc on Read the doc the latest changes has not always been put there. I think that having it twice doesn't help to maintain it. 

I would suggest we remove one to keep everything up-to-date in only one place.

WDYT

**Comment by avelis** [comment]
@triat I am fine with just the README.md for now. Seems like less effort to maintain all around. I do like the concept of readthedocs.org but then have to shift all updates from readme,d to the index.md.

I will be honest and say that I keep forgetting to update those docs.

**Comment by triat** [comment]
@avelis that's my whole point :) I try to keep everything up to date but 2 docs ... Let's keep readthedocs aside for now, we can even remove it and take it back from the git history if needed.

Do you agree?

**Comment by avelis** [comment]
Ok sounds good!
