### ISSUE TITLE
Migrations conflict

### ISSUE THREAD

**Issue by jeffryadityatama** [aschn/drf-tracking#112]
I'm using Django 1.11.7, and using `drf-tracing` at latest master branch (b753c5e).
When I run `python manage.py makemigrations`, I got the following conflict error:
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0006_auto_20180315_1442, 0006_view_and_view_method_nullable in rest_framework_tracking).
To fix them run 'python manage.py makemigrations --merge'
```
I can solve it by running `python manage.py makemigrations --merge` but thats a bit inconvenient when using travis, since I need to run `makemigrations` every time the build process running. Is there any plan to fix this?

**Comment by avelis** [comment]
@jeffryadityatama Would PR #109 address your issue?

**Comment by jeffryadityatama** [comment]
@avelis Aha, that should fix my issue. Any plan to merge that PR?

**Comment by avelis** [comment]
@jeffryadityatama just merged it in.

**Comment by jeffryadityatama** [comment]
@avelis Thanks for your fast response! Let's close this issue
