### ISSUE TITLE
django 2 compatible

### ISSUE THREAD

**Issue by singhravi1** [aschn/drf-tracking#115]
We have to make this compatible with django 2.
There are various things that are deprecated, such as, is_authenticated is not a function anymore.

**Comment by silasserner** [comment]
Hello, when will you release a version containing these changes.
Regards
Silas

**Comment by triat** [comment]
I think we would require the help of @avelis

**Comment by avelis** [comment]
Release made: https://pypi.org/project/drf-tracking/1.5.0/
