### ISSUE TITLE
why this line is needed?

### ISSUE THREAD

**Issue by singhravi1** [aschn/drf-tracking#128]
Hi everyone,

Can anyone please explain why the following line is needed?

https://github.com/aschn/drf-tracking/blob/57344c65fe39923ab2debbf581d9fd0dbc46b2fa/rest_framework_tracking/base_mixins.py#L50

Thanks

**Comment by avelis** [comment]
The oldest origin point I could find is llinked below. I presume it allows the middleware to go up the change to continue on before working on actual logging.

https://github.com/aschn/drf-tracking/blame/5425159ec6639101c512c7b8818d5f1573b2e1ef/rest_framework_tracking/mixins.py#L87

**Comment by singhravi1** [comment]
But it is in the base class and basically overriding itself?

**Comment by singhravi1** [comment]
Oh, okay. Now i get it. I was confused as i did not know about the finalize_rezponse method in APIView and the super was called on Base Exceprion class which is the current class only.
