### ISSUE TITLE
http 500 to be handled

### ISSUE THREAD

**Issue by zatarus** [aschn/drf-tracking#16]
Any http 500 error causes log to have status code not assigned and response ms to 0. It would be nice to see the trace instead.

**Comment by aschn** [comment]
@zatarus want to take a look at PR #18 and see if it works for you? thanks :)

**Comment by zatarus** [comment]
Hey @aschn, thank you for taking time on this. I have found a behavior with drf, where if response is empty, it will raise the exception itself (regardless of debug mode) and prevent mixin's handling. Here is the location:

https://github.com/tomchristie/django-rest-framework/blob/78e4ea0d6e88a7b355ec3e790ef0e8f95859ca2d/rest_framework/views.py#L434

Default exception function by restframework also explains it as:

> Any unhandled exceptions may return `None`, which will cause a 500 error to be raised.

so calling super handle_exception seems unreliable for anything that is not handled such as ParseError(), or raise of any exception other than APIException. In my case, I just wanted to cover all :)

Do you agree if calling super should be wrapped in try/except or I should implement my own exception class to wrap them all? If secondary, that implementation is fair already.

**Comment by triat** [comment]
I think this one can be closed now with the new PR that you just merged @avelis

**Comment by avelis** [comment]
@triat I will close it when I get a release out. Keeps me honest to get it out.

**Comment by triat** [comment]
No worries :) I'm just trying to follow things correctly :) Thanks for your time

**Comment by avelis** [comment]
Addressed in [version 1.2.0](https://github.com/aschn/drf-tracking/releases/tag/1.2.0) release.
