### ISSUE TITLE
Add support for MySQL backend

### ISSUE THREAD

**Issue by dvinegla** [aschn/drf-tracking#19]
Add support for MySQL backend 
https://github.com/aschn/drf-tracking/commit/83448b73c2f954b420b6a31a19fa26e113a48246
was dropped in  split migrations
https://github.com/aschn/drf-tracking/commit/b138fcbcbcf798310b97186269bac148c3febe3c

**Comment by avelis** [comment]
The problem revolves around the `query_params` field with `db_index` set to `True`. There is an MySQL InnoDB restriction that text field based indices must have a defined length.

So, in theory you could either drop the `db_index=True` or specify a length parameter for the index to enforce.

I am in favor of dropping the index requirement.

**Comment by avelis** [comment]
Addressed in release: https://github.com/aschn/drf-tracking/releases/tag/1.0.0

**Comment by avelis** [comment]
Addressed in the following release: https://github.com/aschn/drf-tracking/releases/tag/1.0.1
