### ISSUE TITLE
User filtering in admin

### ISSUE THREAD

**Issue by dvinegla** [aschn/drf-tracking#20]
This filter 
list_filter = (**'user'**, 'path', 'method', 'status_code')
is a bit annoying if you have +1000 users.

and can you add 
raw_id_fields = ('user', )
to APIRequestLogAdmin class ?

**Comment by zatarus** [comment]
I have a pending pull request on first part of the suggestio:. https://github.com/aschn/drf-tracking/pull/21

**Comment by avelis** [comment]
@dvinegla I have merged the PR provided by @zatarus .

**Comment by avelis** [comment]
Addressed in release: https://github.com/aschn/drf-tracking/releases/tag/1.0.0
