### ISSUE TITLE
MySQL error: BLOB/TEXT column 'query_params'  used in key specification without a key length"

### ISSUE THREAD

**Issue by victorx98** [aschn/drf-tracking#29]
Here is what I learned from MySQL manual (http://dev.mysql.com/doc/refman/5.7/en/create-index.html):
"Prefixes must be specified for BLOB and TEXT column indexes."

**Comment by avelis** [comment]
@victorx98 For clarification is this related to #19 ? Whereby the db_index argument for the query_params field does not have length argument defined?

**Comment by avelis** [comment]
This _should_ be addressed the following release: https://github.com/aschn/drf-tracking/releases/tag/1.0.0

If not please re-open

**Comment by mszacun** [comment]
Hi, for me problem still exists, index on query_params is still there in migration, and index length parameter is missing. I get exactly the same error:
`django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'query_params' used in key specification without a key length")  `

**Comment by avelis** [comment]
@mszacun I misread the migration file change. It updated another field and not the query_params field. Sorry about that.

**Comment by mszacun** [comment]
Are you going to make a release? I would like to use this package in my project.

**Comment by avelis** [comment]
@mszacun Yes, I plan to make another release by end of week.

**Comment by victorx98** [comment]
I forked the repo and made some changes(text field to char filed) myself: https://github.com/victorx98/drf-tracking/commit/efc2350b202d78cc2db9aed2763e381bb84ccae1

So far it is working fine to me.

Not sure what is in the upcoming release? I may want switch to it.

**Comment by avelis** [comment]
@victorx98 I made some notes on the last release viewable [here](https://github.com/aschn/drf-tracking/releases/tag/1.0.0). With that said, there is still a necessary release I need to make to finally address MySQL support.

A lot of thanks goes to @jameshiew his time and contribution's to this repo in getting MySQL support going and tested via TravisCI.
