### ISSUE TITLE
Simple way to disable/limit the size of the response stored in the database

### ISSUE THREAD

**Issue by SimKennedy** [aschn/drf-tracking#43]
Hi,

Thanks for the useful plugin!

Since some of our API responses can be large, the log table is becoming slow to load due to the size of the response column. They are cropped to [204K], (I think due to Django/postgres?), but this  is still a lot and means we have to update the column data manually to get sensible performance.

Is there an easy way to turn off or limit the size of the response stored?

Cheers

Sim

**Comment by avelis** [comment]
@SimKennedy There is no drf-tracking setting to disable storage based on response body to be stored. You could use Django's `pre_save` signal to listen to the model save and do some data pre-processing before the save hits the db. Thats might best immediate suggestion.

**Comment by SimKennedy** [comment]
Thanks @avelis! That worked perfectly. :+1: 

Sorry for the noob question. I am still learning Django and didn't know how easy it is to intercept signals.

**Comment by avelis** [comment]
No apologies needed. Glad it worked out!
