### ISSUE TITLE
Is it possible to call logging when status is 500, 404 etc only?

### ISSUE THREAD

**Issue by Ratak** [aschn/drf-tracking#52]
Or to call logging when some conditions were fulfilled.
Mixin logs all requests to the view :(

**Comment by avelis** [comment]
@Ratak The short answer is no. You could listen to a post save signal and check the status of logged data to only be 500 or 404 and delete anything else.

If you can think of a PR to enable a response status code filter I would be able happy to take a look at it and merge it in.

**Comment by frankie567** [comment]
@avelis I've something about this in an [experimental branch](https://github.com/frankie567/drf-tracking/tree/drf-tracking-extended).

Basically, we introduce methods called at the beginning of the request and before returning response that return `true` if the request should be logged. Doing this, we allow developers to override these methods and introduce their own logic (e.g. log only response with a `status_code >= 400`).

If you're interested, I could propose this as a PR.

**Comment by avelis** [comment]
@frankie567 Yeah, make it a PR and I can take a look and potentially merge it in.
