### ISSUE TITLE
1.2.0 wheel on pypi contains 1.3.1 code!!!

### ISSUE THREAD

**Issue by gbataille** [aschn/drf-tracking#64]
This seems to have happened yesterday, the wheel of 1.2.0 was updated but the content is not right.

![image](https://user-images.githubusercontent.com/1113065/28958060-07213866-78f5-11e7-9b24-1a8be2a51548.png)

**Comment by avelis** [comment]
Yes

**Comment by avelis** [comment]
@gbataille Thanks for pointing this out. I will get this sorted out. This was not my intention at all. I created 1.3.0 but forgot to update the version string in the project. Therefore the upload to PyPi of the wheel is incorrect. I will take that down and try to un tag the 1.3.0 release.

**Comment by gbataille** [comment]
thanks.
This drove me crazy. all my builds started to fail all of a sudden (with
fresh venv).
The issue is the PR I submitted. Tom's code to obfuscate passwords actually
does not work with drf test, for a reason that slightly eludes me for the
moment.
The fix works though.

**Comment by avelis** [comment]
@gbataille I have remove the published wheel but left 1.2.0 that was uploaded on March 8th. This should bring it back to what it was before the upload.

**Comment by avelis** [comment]
@gbataille I am going to close this issue.
