### ISSUE TITLE
[STOPPED] Elastic search compatibility

### ISSUE THREAD

**Issue by triat** [aschn/drf-tracking#69]
I'm currently working on a possibility to store data either in the database or in a elastic search cluster.

If you have idea or input regarding this feature, please share your thoughts here.

**Comment by avelis** [comment]
First off, Thanks for working on this.

Some input:
1. The ability to augment the ES mapping from the standard mapping you might come up with when serializing an APIRequestLog to an ES cluster. Not sure if that is even worth while but might be something to consider.
2. Ensure data sending to an ES cluster uses the bulk API. However, this depends on volume though.
3. The ability to use a method override/signal to potentially filter out data I wouldn't care to send to an ES cluster.
4. A nice to have would be document/create commands to orchestrate management of a cluster. If this requires leaning on another library I think that's fine.

Thanks again.

**Comment by triat** [comment]
Hey @avelis, 

Thanks for your input. 
> The ability to augment the ES mapping from the standard mapping you might come up with when serializing an APIRequestLog to an ES cluster. Not sure if that is even worth while but might be something to consider.

For the first shot, I keep everything really simple and as I'm still not a super user of ES (almost never used it before) I don't really see exactly what you mean by that but I'm sure if it's needed we can work on it later

> Ensure data sending to an ES cluster uses the bulk API. However, this depends on volume though.

How do you see that ? because I planned to send an event to ES every time a log is generated, otherwise it means that I have to store it somewhere, check how many messages I have and then trigger the bulk

> The ability to use a method override/signal to potentially filter out data I wouldn't care to send to an ES cluster.

Is it not how it works already ? We just change where you register the log right ?

> A nice to have would be document/create commands to orchestrate management of a cluster. If this requires leaning on another library I think that's fine.

I'll keep it for later if you don't mind, again, I'm not an experimented user of ES so I wouldn't try to go too far for the first version if you don't mind
