### ISSUE TITLE
Fail for Bulk Create

### ISSUE THREAD

**Issue by billytotochan** [aschn/drf-tracking#78]
In `venv/lib/python3.5/site-packages/rest_framework_tracking/mixins.py", line 134, in _clean_data`

`if SENSITIVE_DATA.search(key):`

`TypeError: expected string or bytes-like object`

```python
  class MyBulkCreate(LoggingMixin, generics.CreateAPIView):

      def create(self, request, *args, **kwargs):

         serializer = serializers.FooBarSerializer(data=data, context=context, many=True)
```
my post data is a json as following:

`   [{"foo": "200" ,"bar": "A", "fufu":"1"},{"foo": "200" ,"bar": "B", "fufu":"1"}]`

When i pass the data through Mixin and it crashed already. I have to skip using the tracking function for all bulk_create api.

Will there any solutions for now?

**Comment by triat** [comment]
I think this is related to the PR #73 but it was never done. 

I think someone will have to take it and post it again

**Comment by triat** [comment]
#80 might fix this one too

**Comment by tselepakis** [comment]
Hi @triat , I think PR #80 solves that problem, too.

**Comment by triat** [comment]
If it's solved, can we close this one ?
