### ISSUE TITLE
IntegrityError response_ms

### ISSUE THREAD

**Issue by tselepakis** [aschn/drf-tracking#79]
Hello all,

I just want to share an issue I had.

There was an exception regarding negative response time. After reading the code a bit I see that you have a justified assumption regarding the [`response_ms` being positive](https://github.com/aschn/drf-tracking/blob/master/rest_framework_tracking/models.py#L18).

The implementation of the duration is straightforward so no surprises there. My solution was to patch the [duration calculation](https://github.com/aschn/drf-tracking/blob/master/rest_framework_tracking/mixins.py#L88) to return 0 if the delta is negative.

Something like this:
`response_timedelta = now() - self.request.log.requested_at`
`response_ms = int(response_timedelta.total_seconds() * 1000)`
`response_ms = max(response_ms, 0)`

I wasn't able to reproduce the issue though.
I was wondering if anyone else have seen something similar.

Thanks

**Comment by avelis** [comment]
@tselepakis Thanks for writing in. If you find it useful to create a PR to handle this scenario. I encourage it and I can merge it in.

**Comment by triat** [comment]
@avelis can we put this one as solved ?
