### ISSUE TITLE
Code looks overcommented

### ISSUE THREAD

**Issue by zenwalker** [aschn/drf-tracking#90]
This may be none of my business, but I think the huge part of comments in this project doesn't make sense because the code is already obvious. They explain nothing and don’t help. Just a noise. My advice is get rid of them. What do you think?

Like this:
<img width="692" alt="screen shot 2017-12-18 at 16 39 39" src="https://user-images.githubusercontent.com/1812128/34109863-f18024cc-e415-11e7-9299-5cc6023c382d.png">

Or this:
<img width="732" alt="screen shot 2017-12-18 at 16 37 57" src="https://user-images.githubusercontent.com/1812128/34109866-f578a69e-e415-11e7-97be-1bf6a0490d46.png">

**Comment by avelis** [comment]
@zenwalker Sounds good to me!
