### ISSUE TITLE
Do a release to fix the actual bug in the version of PYPI

### ISSUE THREAD

**Issue by triat** [aschn/drf-tracking#95]
Hey @avelis,

I think it's would be really great to have a new version released on PYPI as the actual one has an important issue. 

Do you think it's possible to do it ? 

Thanks

**Comment by avelis** [comment]
@triat Would a maintenance release work or is it better to do a minor?

**Comment by avelis** [comment]
@triat Would a maintenance release work or is it better to do a minor?

**Comment by triat** [comment]
I guess a minor is better if you don't mind
